# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_max_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_max_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_max_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_max_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

roll_mean_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_mean_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_mean_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_mean_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

roll_median_numeric_vector <- function(x_, n) {
    .Call('RcppRoll_roll_median_numeric_vector', PACKAGE = 'RcppRoll', x_, n)
}

roll_median_numeric_matrix <- function(A_, n) {
    .Call('RcppRoll_roll_median_numeric_matrix', PACKAGE = 'RcppRoll', A_, n)
}

roll_min_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_min_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_min_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_min_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

roll_prod_numeric_vector <- function(x_, n) {
    .Call('RcppRoll_roll_prod_numeric_vector', PACKAGE = 'RcppRoll', x_, n)
}

roll_prod_numeric_matrix <- function(A_, n) {
    .Call('RcppRoll_roll_prod_numeric_matrix', PACKAGE = 'RcppRoll', A_, n)
}

roll_sd_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_sd_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_sd_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_sd_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

roll_stddev_numeric_vector <- function(x_, n) {
    .Call('RcppRoll_roll_stddev_numeric_vector', PACKAGE = 'RcppRoll', x_, n)
}

roll_stddev_numeric_matrix <- function(A_, n) {
    .Call('RcppRoll_roll_stddev_numeric_matrix', PACKAGE = 'RcppRoll', A_, n)
}

roll_sum_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_sum_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_sum_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_sum_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

roll_var_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_var_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_var_numeric_matrix <- function(A, n) {
    .Call('RcppRoll_roll_var_numeric_matrix', PACKAGE = 'RcppRoll', A, n)
}

