# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roll_mean_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_mean_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_mean_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_mean_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_sum_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_sum_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_sum_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_sum_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_var_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_var_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_var_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_var_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_sd_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_sd_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_sd_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_sd_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_max_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_max_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_max_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_max_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_min_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_min_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_min_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_min_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

roll_median_numeric_vector <- function(x, n) {
    .Call('RcppRoll_roll_median_numeric_vector', PACKAGE = 'RcppRoll', x, n)
}

roll_median_numeric_matrix <- function(A, n, by_column) {
    .Call('RcppRoll_roll_median_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column)
}

roll_prod_numeric_vector <- function(x, n, weights) {
    .Call('RcppRoll_roll_prod_numeric_vector', PACKAGE = 'RcppRoll', x, n, weights)
}

roll_prod_numeric_matrix <- function(A, n, by_column, weights) {
    .Call('RcppRoll_roll_prod_numeric_matrix', PACKAGE = 'RcppRoll', A, n, by_column, weights)
}

