functions <- c("mean", "median", "min", "max", "prod", "sum", "sd", "var")
trimLeft <- function(x) {
  gsub("^[[:space:]]", "", x, perl = TRUE)
}

## Generate Rcpp exports

preamble <- trimLeft("
#include <Rcpp.h>
using namespace Rcpp;
")

generator <- trimLeft("
// [[Rcpp::export(.RcppRoll_%s)]]
SEXP roll_%s(SEXP x, int n, SEXP weights, SEXP pad, bool by_column, bool normalize) {

  if (Rf_isMatrix(x)) {
    return RcppRoll::roll_matrix_with(
        RcppRoll::%s_f(), NumericMatrix(x), weights, n, pad, normalize);
  } else {
    return RcppRoll::roll_vector_with(
        RcppRoll::%s_f(), NumericVector(x), weights, n, pad, normalize);
  }

}
")

gen <- unlist(lapply(functions, function(x) {
  gsub("%s", x, generator, fixed = TRUE)
}))

has_flag <- function(content, flag) {
  any(grepl(flag, content, fixed = TRUE))
}

content <- readLines("src/rollit.cpp")
begin_flag <- "// Begin auto-generated exports (internal/make_exports.R)"
end_flag <- "// End auto-generated exports (internal/make_exports.R)"
if (has_flag(content, begin_flag) && has_flag(content, end_flag)) {
  content <- content[-c(`:`(
    grep(begin_flag, content, fixed = TRUE),
    grep(end_flag, content, fixed = TRUE)
  ))]
}

output <- c(content,
            "",
            begin_flag,
            "",
            gen,
            end_flag
)

cat(output, file = "src/rollit.cpp", sep = "\n")

## Generate R wrapper functions
header <- trimLeft("
## Auto-generated by internal/make_exports.R
")
wrapper <- trimLeft("
##' @rdname RcppRoll
##' @export
roll_%s <- function(x, n, weights = rep(1,n), pad = NULL, by.column = TRUE, normalize = FALSE) {
  return(.RcppRoll_%s(x, weights, pad, by.column, normalize))
}
")

wrappers <- unlist(lapply(functions, function(x) {
  gsub("%s", x, wrapper, fixed = TRUE)
}))

cat(c(header, wrappers), file = "R/rollit_generated.R", sep = "\n")

