functions <- c("mean", "median", "min", "max", "prod", "sum", "sd", "var")
trimLeft <- function(x) {
  gsub("^[[:space:]]", "", x, perl = TRUE)
}

## Generate Rcpp exports

preamble <- trimLeft("
#include <Rcpp.h>
using namespace Rcpp;
")

generator <- trimLeft("
// [[Rcpp::export(.RcppRoll_%s)]]
SEXP roll_%s(SEXP x, int n, SEXP weights, NumericVector fill_, bool partial, String align) {

  RcppRoll::Fill fill(fill_);
  if (Rf_isMatrix(x)) {
    return RcppRoll::roll_matrix_with(
        RcppRoll::%s_f(), NumericMatrix(x), n, weights, fill, partial, align);
  } else {
    return RcppRoll::roll_vector_with(
        RcppRoll::%s_f(), NumericVector(x), n, weights, fill, partial, align);
  }

}
")

gen <- unlist(lapply(functions, function(x) {
  gsub("%s", x, generator, fixed = TRUE)
}))

has_flag <- function(content, flag) {
  any(grepl(flag, content, fixed = TRUE))
}

content <- readLines("src/rollit.cpp")
begin_flag <- "// Begin auto-generated exports (internal/make_exports.R)"
end_flag <- "// End auto-generated exports (internal/make_exports.R)"
if (has_flag(content, begin_flag) && has_flag(content, end_flag)) {
  content <- content[-c(`:`(
    grep(begin_flag, content, fixed = TRUE),
    grep(end_flag, content, fixed = TRUE)
  ))]
}

output <- c(content,
            "",
            begin_flag,
            "",
            gen,
            end_flag
)

cat(output, file = "src/rollit.cpp", sep = "\n")

## Generate R wrapper functions
header <- trimLeft("
## Auto-generated by internal/make_exports.R
")
wrapper <- trimLeft("
##' @rdname RcppRoll
##' @export
roll_%s <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c(\"center\", \"left\", \"right\")) {
  return(.RcppRoll_%s(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}
")

wrappers <- unlist(lapply(functions, function(x) {
  gsub("%s", x, wrapper, fixed = TRUE)
}))

cat(c(header, wrappers), file = "R/rollit_generated.R", sep = "\n")
