functions <- c("mean", "median", "min", "max", "prod", "sum", "sd", "var")
trimLeft <- function(x) {
  gsub("^[[:space:]]", "", x, perl = TRUE)
}

## Generate Rcpp exports

preamble <- trimLeft("
#include <Rcpp.h>
using namespace Rcpp;
")

generator <- trimLeft("
// [[Rcpp::export(.RcppRoll_%s)]]
SEXP roll_%s(SEXP x, int n, NumericVector weights,
  int by, NumericVector fill_, bool partial, String align, bool normalize) {

  RcppRoll::Fill fill(fill_);
  if (Rf_isMatrix(x)) {
    return RcppRoll::roll_matrix_with(
        RcppRoll::%s_f(), NumericMatrix(x), n, weights, by, fill, partial, align, normalize);
  } else {
    return RcppRoll::roll_vector_with(
        RcppRoll::%s_f(), NumericVector(x), n, weights, by, fill, partial, align, normalize);
  }

}
")

gen <- unlist(lapply(functions, function(x) {
  gsub("%s", x, generator, fixed = TRUE)
}))

has_flag <- function(content, flag) {
  any(grepl(flag, content, fixed = TRUE))
}

content <- readLines("src/rollit.cpp")
begin_flag <- "// Begin auto-generated exports (internal/make_exports.R)"
end_flag <- "// End auto-generated exports (internal/make_exports.R)"
if (has_flag(content, begin_flag) && has_flag(content, end_flag)) {
  content <- content[-c(`:`(
    grep(begin_flag, content, fixed = TRUE),
    grep(end_flag, content, fixed = TRUE)
  ))]
}

output <- c(content,
            begin_flag,
            "",
            gen,
            end_flag
)

cat(output, file = "src/rollit.cpp", sep = "\n")

## Generate R wrapper functions
header <- trimLeft("
## Auto-generated by internal/make_exports.R

##' RcppRoll
##'
##' The following functions are provided directly by \\code{RcppRoll}.
##'
##' @name RcppRoll-exports
##' @param x A numeric vector or a numeric matrix.
##' @param n A window size.
##' @param weights A vector of length \\code{n}, giving the weights for each
##'   element within a window.
##' @param fill Either an empty vector (no fill), or a vector (recycled to)
##'   length 3 giving left, middle and right fills.
##' @param partial Partial application? Currently unimplemented.
##' @param align Align windows on the \\code{\"left\"}, \\code{\"middle\"} or
##'   \\code{\"right\"}.
NULL
")

wrapper <- trimLeft("
##' @rdname RcppRoll-exports
##' @export
roll_%s <- function(x, n, weights = NULL, by = 1L,
  fill = numeric(0), partial = FALSE,
  align = c(\"center\", \"left\", \"right\"), normalize = TRUE) {
  return(.RcppRoll_%s(
    x,
    as.integer(n),
    as.numeric(weights),
    as.integer(by),
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align)),
    as.logical(normalize)
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_%sr <- function(x, n, weights = NULL, by = 1L,
  fill = NA, partial = FALSE, align = \"right\", normalize = TRUE) {
  return(.RcppRoll_%s(
    x,
    as.integer(n),
    as.numeric(weights),
    as.integer(by),
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align)),
    as.logical(normalize)
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_%sl <- function(x, n, weights = NULL, by = 1L,
  fill = NA, partial = FALSE, align = \"left\", normalize = TRUE) {
  return(.RcppRoll_%s(
    x,
    as.integer(n),
    as.numeric(weights),
    as.integer(by),
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align)),
    as.logical(normalize)
  ))
}
")

wrappers <- unlist(lapply(functions, function(x) {
  gsub("%s", x, wrapper, fixed = TRUE)
}))

cat(c(header, wrappers), file = "R/rollit_generated.R", sep = "\n")
