# Auto-generated by internal/make-exports.R

#' RcppRoll
#'
#' Efficient windowed / rolling operations. Each function
#' here applies an operation over a moving window of
#' size \code{n}, with (customizable) weights specified
#' through \code{weights}.
#'
#' The functions postfixed with \code{l} and \code{r}
#' are convenience wrappers that set \strong{l}eft
#' / \strong{r}ight alignment of the windowed operations.
#'
#' @name RcppRoll-exports
#' @param x A numeric vector or a numeric matrix.
#' @param n The window size. Ignored when \code{weights} is non-\code{NULL}.
#' @param weights A vector of length \code{n}, giving the weights for each
#'   element within a window. If \code{NULL}, we take unit weights of width \code{n}.
#' @param by Calculate at every \code{by}-th point rather than every point.
#' @param fill Either an empty vector (no fill), or a vector (recycled to)
#'   length 3 giving left, middle and right fills.
#' @param partial Partial application? Currently unimplemented.
#' @param align Align windows on the \code{"left"}, \code{"middle"} or
#'   \code{"right"}.
#' @param normalize Normalize window weights, such that they sum to \code{n}.
#' @param na.rm Remove missing values?
NULL
