# Auto-generated by internal/make-exports.R

#' RcppRoll
#'
#' Efficient windowed / rolling operations. Each function
#' here applies an operation over a moving window of
#' size \code{n}, with (customizable) weights specified
#' through \code{weights}.
#'
#' The functions postfixed with \code{l} and \code{r}
#' are convenience wrappers that set \strong{l}eft
#' / \strong{r}ight alignment of the windowed operations.
#'
#' @name RcppRoll-exports
#' @param x A numeric vector or a numeric matrix.
#' @param n A positive integer scalar giving the window size. Ignored when
#'   \code{weights} is non-\code{NULL}.
#' @param weights A non-empty vector of length \code{n}, giving the weights for
#'   each element within a window. If \code{NULL}, we take unit weights of width
#'   \code{n}. For an even window with uniform weights, \code{roll_median()}
#'   returns the lower of the two central values; the unweighted median instead
#'   averages those values. Variance and standard deviation require finite,
#'   non-negative frequency weights.
#' @param by A positive integer scalar. Calculate at every \code{by}-th point
#'   rather than every point.
#' @param fill Either an empty vector (no fill), or a vector (recycled to)
#'   length 3 giving left, center and right fills.
#' @param partial A single non-missing logical. Compute windows at the edges of
#'   \code{x} over however many elements are in range, rather than filling them?
#'   Cannot be combined with \code{weights}, and \code{fill} does not apply.
#' @param align Align windows on the \code{"left"}, \code{"center"} or
#'   \code{"right"}.
#' @param normalize A single non-missing logical. Normalize window weights,
#'   such that they sum to \code{n}? Normalized weights must be finite and have
#'   a finite, non-zero sum.
#' @param na.rm A single non-missing logical. Remove missing values?
NULL

# Argument checking shared by every wrapper below. 'missing_n' and
# 'missing_fill' come from the caller, since missing() only speaks for the frame
# it is called in; conditions are raised against the caller too, so that a user
# sees the roll_* call they made rather than this helper. Returns the window
# size to use, which 'weights' overrides when the two disagree.
checkRollArgs <- function(n, weights, by, partial, normalize, na.rm,
                          missing_n, missing_fill) {

  call <- sys.call(-1L)

  isPositiveInteger <- function(value) {
    (is.integer(value) || is.double(value)) &&
      !is.object(value) &&
      length(value) == 1L &&
      !is.na(value) &&
      is.finite(value) &&
      value >= 1 &&
      value <= .Machine$integer.max &&
      value == floor(value)
  }

  if (!isPositiveInteger(n)) {
    stop(simpleError("'n' should be a positive integer scalar", call))
  }
  n <- as.integer(n)

  if (!isPositiveInteger(by)) {
    stop(simpleError("'by' should be a positive integer scalar", call))
  }

  isScalarLogical <- function(value) {
    is.logical(value) && length(value) == 1L && !is.na(value)
  }

  for (name in c("partial", "normalize", "na.rm")) {
    if (!isScalarLogical(get(name))) {
      stop(simpleError(sprintf("'%s' should be TRUE or FALSE", name), call))
    }
  }

  if (!is.null(weights)) {
    weights_n <- length(weights)
    if (!isPositiveInteger(weights_n)) {
      stop(simpleError(
        "'weights' should be non-empty and define a positive integer window size",
        call))
    }
  }

  if (partial) {
    if (!is.null(weights))
      stop(simpleError(
        "'partial = TRUE' is not supported together with 'weights'", call))
    if (!missing_fill)
      warning(simpleWarning("'fill' is ignored when 'partial = TRUE'", call))
  }

  if (!missing_n && !is.null(weights) && weights_n != n) {
    warning(simpleWarning(sprintf(
      "'n' is ignored when 'weights' is supplied; using 'n = %i' rather than 'n = %i'",
      weights_n, n
    ), call))
  }

  if (!is.null(weights))
    n <- weights_n

  n
}
