# Auto-generated by internal/make-exports.R

#' RcppRoll
#'
#' Efficient windowed / rolling operations. Each function
#' here applies an operation over a moving window of
#' size \code{n}, with (customizable) weights specified
#' through \code{weights}.
#'
#' The functions postfixed with \code{l} and \code{r}
#' are convenience wrappers that set \strong{l}eft
#' / \strong{r}ight alignment of the windowed operations.
#'
#' @name RcppRoll-exports
#' @param x A numeric vector or a numeric matrix.
#' @param n The window size. Ignored when \code{weights} is non-\code{NULL}.
#' @param weights A vector of length \code{n}, giving the weights for each
#'   element within a window. If \code{NULL}, we take unit weights of width \code{n}.
#' @param by Calculate at every \code{by}-th point rather than every point.
#' @param fill Either an empty vector (no fill), or a vector (recycled to)
#'   length 3 giving left, middle and right fills.
#' @param partial Compute windows at the edges of \code{x} over however
#'   many elements are in range, rather than filling them? Cannot be
#'   combined with \code{weights}, and \code{fill} does not apply.
#' @param align Align windows on the \code{"left"}, \code{"center"} or
#'   \code{"right"}.
#' @param normalize Normalize window weights, such that they sum to \code{n}.
#' @param na.rm Remove missing values?
NULL

# Argument checking shared by every wrapper below. 'missing_n' and
# 'missing_fill' come from the caller, since missing() only speaks for the frame
# it is called in; conditions are raised against the caller too, so that a user
# sees the roll_* call they made rather than this helper. Returns the window
# size to use, which 'weights' overrides when the two disagree.
checkRollArgs <- function(n, weights, partial, missing_n, missing_fill) {

  call <- sys.call(-1L)

  if (!is.logical(partial) || length(partial) != 1L || is.na(partial)) {
    stop(simpleError("'partial' should be TRUE or FALSE", call))
  }

  if (partial) {
    if (!is.null(weights))
      stop(simpleError(
        "'partial = TRUE' is not supported together with 'weights'", call))
    if (!missing_fill)
      warning(simpleWarning("'fill' is ignored when 'partial = TRUE'", call))
  }

  if (!missing_n && !is.null(weights) && !isTRUE(length(weights) == n)) {
    warning(simpleWarning(sprintf(
      "'n' is ignored when 'weights' is supplied; using 'n = %i' rather than 'n = %i'",
      length(weights), as.integer(n)
    ), call))
    n <- length(weights)
  }

  n
}
