// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// roll_mean
SEXP roll_mean(SEXP x, int n, SEXP weights, SEXP pad, bool by_column, bool normalize);
RcppExport SEXP RcppRoll_roll_mean(SEXP xSEXP, SEXP nSEXP, SEXP weightsSEXP, SEXP padSEXP, SEXP by_columnSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< SEXP >::type weights(weightsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type pad(padSEXP );
        Rcpp::traits::input_parameter< bool >::type by_column(by_columnSEXP );
        Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP );
        SEXP __result = roll_mean(x, n, weights, pad, by_column, normalize);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
