# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.RcppRoll_mean <- function(x, n, weights, pad, by_column, normalize) {
    .Call('RcppRoll_roll_mean', PACKAGE = 'RcppRoll', x, n, weights, pad, by_column, normalize)
}

