# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.RcppRoll_mean <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_mean', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_median <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_median', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_min <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_min', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_max <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_max', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_prod <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_prod', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_sum <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_sum', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_sd <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_sd', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

.RcppRoll_var <- function(x, n, weights, by, fill_, partial, align, normalize, na_rm) {
    .Call('RcppRoll_roll_var', PACKAGE = 'RcppRoll', x, n, weights, by, fill_, partial, align, normalize, na_rm)
}

