## Auto-generated by internal/make_exports.R

##' RcppRoll
##'
##' The following functions are provided directly by \code{RcppRoll}.
##'
##' @name RcppRoll-exports
##' @param x A numeric vector or a numeric matrix.
##' @param n A window size.
##' @param weights A vector of length \code{n}, giving the weights for each
##'   element within a window.
##' @param fill Either an empty vector (no fill), or a vector (recycled to)
##'   length 3 giving left, middle and right fills.
##' @param partial Partial application? Currently unimplemented.
##' @param align Align windows on the \code{"left"}, \code{"middle"} or
##'   \code{"right"}.
NULL

##' @rdname RcppRoll-exports
##' @export
roll_mean <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_mean(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_meanr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_mean(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_meanl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_mean(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_median <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_median(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_medianr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_median(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_medianl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_median(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_min <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_min(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_minr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_min(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_minl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_min(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_max <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_max(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_maxr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_max(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_maxl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_max(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_prod <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_prod(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_prodr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_prod(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_prodl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_prod(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_sum <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_sum(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_sumr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_sum(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_suml <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_sum(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_sd <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_sd(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_sdr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_sd(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_sdl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_sd(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_var <- function(x, n, weights = NULL, fill = numeric(0), partial = FALSE,
                    align = c("center", "left", "right")) {
  return(.RcppRoll_var(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_varr <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "right") {
  return(.RcppRoll_var(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

##' @rdname RcppRoll-exports
##' @export
roll_varl <- function(x, n, weights = NULL, fill = NA, partial = FALSE,
                     align = "left") {
  return(.RcppRoll_var(
    x,
    as.integer(n),
    weights,
    as.numeric(fill),
    as.logical(partial),
    as.character(match.arg(align))
  ))
}

